/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.14.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QFrame>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QLabel *label_2;
    QLineEdit *A1;
    QLineEdit *B1;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_5;
    QLineEdit *C1;
    QLabel *label_6;
    QLabel *label_7;
    QLineEdit *Sum1;
    QLineEdit *Sum2;
    QLineEdit *A2;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QLineEdit *C2;
    QLineEdit *B2;
    QLineEdit *B3;
    QLineEdit *Sum3;
    QLabel *label_14;
    QLineEdit *C3;
    QLabel *label_15;
    QLabel *label_16;
    QLineEdit *A3;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_20;
    QPushButton *pushButton_2;
    QFrame *line;
    QFrame *line_2;
    QFrame *line_3;
    QFrame *line_4;
    QFrame *line_5;
    QFrame *line_6;
    QFrame *line_7;
    QFrame *line_8;
    QPushButton *pushButton_3;
    QLabel *Show_A1;
    QLabel *Show_A2;
    QLabel *Show_A3;
    QLabel *Show_B1;
    QLabel *Show_B2;
    QLabel *Show_B3;
    QLabel *Show_C1;
    QLabel *Show_C2;
    QLabel *Show_C3;
    QLabel *Show_C3_1;
    QFrame *line_9;
    QLabel *Show_Sum3_1;
    QLabel *Show_Sum1_1;
    QLabel *Show_B1_1;
    QLabel *Show_B3_1;
    QFrame *line_10;
    QFrame *line_11;
    QLabel *Show_Sum2_1;
    QLabel *Show_C1_1;
    QFrame *line_12;
    QLabel *Show_C2_1;
    QFrame *line_13;
    QFrame *line_14;
    QFrame *line_15;
    QFrame *line_16;
    QLabel *Show_B2_1;
    QLabel *Show_Sum2_2;
    QFrame *line_17;
    QFrame *line_18;
    QLabel *Show_C1_2;
    QLabel *Show_A3_2;
    QLabel *Show_A2_2;
    QFrame *line_19;
    QFrame *line_20;
    QLabel *Show_Sum3_2;
    QLabel *Show_A1_2;
    QFrame *line_21;
    QLabel *Show_C2_2;
    QLabel *Show_Sum1_2;
    QFrame *line_22;
    QFrame *line_23;
    QFrame *line_25;
    QLabel *Show_C3_2;
    QLabel *Show_Sum3_3;
    QLabel *Show_B1_3;
    QLabel *Show_B2_3;
    QFrame *line_24;
    QFrame *line_26;
    QLabel *Show_A1_3;
    QFrame *line_27;
    QLabel *Show_A3_3;
    QLabel *Show_A2_3;
    QLabel *Show_B3_3;
    QLabel *Show_Sum2_3;
    QFrame *line_28;
    QFrame *line_29;
    QFrame *line_30;
    QLabel *Show_Sum1_3;
    QFrame *line_31;
    QFrame *line_32;
    QLabel *Show_A1_5;
    QPushButton *pushButton;
    QLabel *Show_D;
    QLabel *Show_A1_10;
    QLabel *Show_D1;
    QLabel *Show_A1_6;
    QLabel *Show_D2;
    QLabel *Show_A1_7;
    QLabel *Show_D3;
    QMenuBar *menubar;
    QStatusBar *statusbar;
    QToolBar *toolBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(780, 567);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        label_2 = new QLabel(centralwidget);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(290, 50, 21, 21));
        QFont font;
        font.setPointSize(16);
        label_2->setFont(font);
        A1 = new QLineEdit(centralwidget);
        A1->setObjectName(QString::fromUtf8("A1"));
        A1->setGeometry(QRect(260, 50, 21, 22));
        B1 = new QLineEdit(centralwidget);
        B1->setObjectName(QString::fromUtf8("B1"));
        B1->setGeometry(QRect(350, 50, 21, 22));
        label_3 = new QLabel(centralwidget);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(380, 40, 21, 41));
        label_3->setFont(font);
        label_4 = new QLabel(centralwidget);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(320, 50, 21, 21));
        label_4->setFont(font);
        label_5 = new QLabel(centralwidget);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(470, 50, 21, 21));
        label_5->setFont(font);
        C1 = new QLineEdit(centralwidget);
        C1->setObjectName(QString::fromUtf8("C1"));
        C1->setGeometry(QRect(440, 50, 21, 21));
        label_6 = new QLabel(centralwidget);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(410, 50, 21, 21));
        label_6->setFont(font);
        label_7 = new QLabel(centralwidget);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(500, 50, 21, 21));
        label_7->setFont(font);
        Sum1 = new QLineEdit(centralwidget);
        Sum1->setObjectName(QString::fromUtf8("Sum1"));
        Sum1->setGeometry(QRect(530, 50, 21, 22));
        Sum2 = new QLineEdit(centralwidget);
        Sum2->setObjectName(QString::fromUtf8("Sum2"));
        Sum2->setGeometry(QRect(530, 90, 21, 22));
        A2 = new QLineEdit(centralwidget);
        A2->setObjectName(QString::fromUtf8("A2"));
        A2->setGeometry(QRect(260, 90, 21, 22));
        label_8 = new QLabel(centralwidget);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(380, 80, 21, 41));
        label_8->setFont(font);
        label_9 = new QLabel(centralwidget);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(410, 90, 21, 21));
        label_9->setFont(font);
        label_10 = new QLabel(centralwidget);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(470, 90, 21, 21));
        label_10->setFont(font);
        label_11 = new QLabel(centralwidget);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(500, 90, 21, 21));
        label_11->setFont(font);
        label_12 = new QLabel(centralwidget);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(320, 90, 21, 21));
        label_12->setFont(font);
        label_13 = new QLabel(centralwidget);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(290, 90, 21, 21));
        label_13->setFont(font);
        C2 = new QLineEdit(centralwidget);
        C2->setObjectName(QString::fromUtf8("C2"));
        C2->setGeometry(QRect(440, 90, 21, 22));
        B2 = new QLineEdit(centralwidget);
        B2->setObjectName(QString::fromUtf8("B2"));
        B2->setGeometry(QRect(350, 90, 21, 22));
        B3 = new QLineEdit(centralwidget);
        B3->setObjectName(QString::fromUtf8("B3"));
        B3->setGeometry(QRect(350, 130, 21, 22));
        Sum3 = new QLineEdit(centralwidget);
        Sum3->setObjectName(QString::fromUtf8("Sum3"));
        Sum3->setGeometry(QRect(530, 130, 21, 22));
        label_14 = new QLabel(centralwidget);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(290, 130, 21, 21));
        label_14->setFont(font);
        C3 = new QLineEdit(centralwidget);
        C3->setObjectName(QString::fromUtf8("C3"));
        C3->setGeometry(QRect(440, 130, 21, 22));
        label_15 = new QLabel(centralwidget);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(320, 130, 21, 21));
        label_15->setFont(font);
        label_16 = new QLabel(centralwidget);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(500, 130, 21, 21));
        label_16->setFont(font);
        A3 = new QLineEdit(centralwidget);
        A3->setObjectName(QString::fromUtf8("A3"));
        A3->setGeometry(QRect(260, 130, 21, 22));
        label_17 = new QLabel(centralwidget);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(410, 130, 21, 21));
        label_17->setFont(font);
        label_18 = new QLabel(centralwidget);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(380, 120, 21, 41));
        label_18->setFont(font);
        label_19 = new QLabel(centralwidget);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(470, 130, 21, 21));
        label_19->setFont(font);
        label_20 = new QLabel(centralwidget);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(220, 30, 41, 121));
        QFont font1;
        font1.setFamily(QString::fromUtf8("Microsoft YaHei Light"));
        font1.setPointSize(60);
        label_20->setFont(font1);
        pushButton_2 = new QPushButton(centralwidget);
        pushButton_2->setObjectName(QString::fromUtf8("pushButton_2"));
        pushButton_2->setGeometry(QRect(310, 180, 186, 41));
        pushButton_2->setStyleSheet(QString::fromUtf8("QPushButton {\n"
"     background-color:  rgb(211, 211, 211);\n"
"     border-style: outset;\n"
"     border-width: 2px;\n"
"     border-radius: 10px;\n"
"     border-color:  rgb(128, 128, 128);\n"
"     font: bold 14px;\n"
"     min-width: 10em;\n"
"     padding: 6px;\n"
" }\n"
"QPushButton:pressed {\n"
"     background-color: rgb(220, 220, 220);\n"
"     border-style: inset;\n"
" }"));
        line = new QFrame(centralwidget);
        line->setObjectName(QString::fromUtf8("line"));
        line->setEnabled(true);
        line->setGeometry(QRect(38, 280, 148, 20));
        QFont font2;
        font2.setPointSize(9);
        font2.setBold(true);
        font2.setWeight(75);
        line->setFont(font2);
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        line_2 = new QFrame(centralwidget);
        line_2->setObjectName(QString::fromUtf8("line_2"));
        line_2->setGeometry(QRect(30, 290, 16, 141));
        line_2->setFrameShape(QFrame::VLine);
        line_2->setFrameShadow(QFrame::Sunken);
        line_3 = new QFrame(centralwidget);
        line_3->setObjectName(QString::fromUtf8("line_3"));
        line_3->setGeometry(QRect(180, 290, 16, 141));
        line_3->setFrameShape(QFrame::VLine);
        line_3->setFrameShadow(QFrame::Sunken);
        line_4 = new QFrame(centralwidget);
        line_4->setObjectName(QString::fromUtf8("line_4"));
        line_4->setEnabled(true);
        line_4->setGeometry(QRect(38, 420, 148, 20));
        line_4->setFont(font2);
        line_4->setFrameShape(QFrame::HLine);
        line_4->setFrameShadow(QFrame::Sunken);
        line_5 = new QFrame(centralwidget);
        line_5->setObjectName(QString::fromUtf8("line_5"));
        line_5->setEnabled(true);
        line_5->setGeometry(QRect(38, 375, 148, 20));
        line_5->setFont(font2);
        line_5->setFrameShape(QFrame::HLine);
        line_5->setFrameShadow(QFrame::Sunken);
        line_6 = new QFrame(centralwidget);
        line_6->setObjectName(QString::fromUtf8("line_6"));
        line_6->setEnabled(true);
        line_6->setGeometry(QRect(38, 327, 148, 20));
        line_6->setFont(font2);
        line_6->setFrameShape(QFrame::HLine);
        line_6->setFrameShadow(QFrame::Sunken);
        line_7 = new QFrame(centralwidget);
        line_7->setObjectName(QString::fromUtf8("line_7"));
        line_7->setGeometry(QRect(80, 290, 16, 141));
        line_7->setFrameShape(QFrame::VLine);
        line_7->setFrameShadow(QFrame::Sunken);
        line_8 = new QFrame(centralwidget);
        line_8->setObjectName(QString::fromUtf8("line_8"));
        line_8->setGeometry(QRect(130, 290, 16, 141));
        line_8->setFrameShape(QFrame::VLine);
        line_8->setFrameShadow(QFrame::Sunken);
        pushButton_3 = new QPushButton(centralwidget);
        pushButton_3->setObjectName(QString::fromUtf8("pushButton_3"));
        pushButton_3->setGeometry(QRect(280, 460, 231, 41));
        pushButton_3->setStyleSheet(QString::fromUtf8("QPushButton {\n"
"     background-color:  rgb(211, 211, 211);\n"
"     border-style: outset;\n"
"     border-width: 2px;\n"
"     border-radius: 10px;\n"
"     border-color:  rgb(128, 128, 128);\n"
"     font: bold 14px;\n"
"     min-width: 10em;\n"
"     padding: 6px;\n"
" }\n"
"QPushButton:pressed {\n"
"     background-color: rgb(220, 220, 220);\n"
"     border-style: inset;\n"
" }"));
        Show_A1 = new QLabel(centralwidget);
        Show_A1->setObjectName(QString::fromUtf8("Show_A1"));
        Show_A1->setGeometry(QRect(40, 300, 41, 31));
        Show_A1->setFont(font);
        Show_A1->setFocusPolicy(Qt::NoFocus);
        Show_A1->setLayoutDirection(Qt::LeftToRight);
        Show_A2 = new QLabel(centralwidget);
        Show_A2->setObjectName(QString::fromUtf8("Show_A2"));
        Show_A2->setGeometry(QRect(40, 350, 41, 31));
        Show_A2->setFont(font);
        Show_A3 = new QLabel(centralwidget);
        Show_A3->setObjectName(QString::fromUtf8("Show_A3"));
        Show_A3->setGeometry(QRect(40, 390, 41, 31));
        Show_A3->setFont(font);
        Show_B1 = new QLabel(centralwidget);
        Show_B1->setObjectName(QString::fromUtf8("Show_B1"));
        Show_B1->setGeometry(QRect(90, 300, 41, 31));
        Show_B1->setFont(font);
        Show_B2 = new QLabel(centralwidget);
        Show_B2->setObjectName(QString::fromUtf8("Show_B2"));
        Show_B2->setGeometry(QRect(90, 350, 41, 31));
        Show_B2->setFont(font);
        Show_B3 = new QLabel(centralwidget);
        Show_B3->setObjectName(QString::fromUtf8("Show_B3"));
        Show_B3->setGeometry(QRect(90, 390, 41, 31));
        Show_B3->setFont(font);
        Show_C1 = new QLabel(centralwidget);
        Show_C1->setObjectName(QString::fromUtf8("Show_C1"));
        Show_C1->setGeometry(QRect(140, 300, 41, 31));
        Show_C1->setFont(font);
        Show_C2 = new QLabel(centralwidget);
        Show_C2->setObjectName(QString::fromUtf8("Show_C2"));
        Show_C2->setGeometry(QRect(140, 350, 41, 31));
        Show_C2->setFont(font);
        Show_C3 = new QLabel(centralwidget);
        Show_C3->setObjectName(QString::fromUtf8("Show_C3"));
        Show_C3->setGeometry(QRect(140, 390, 41, 31));
        Show_C3->setFont(font);
        Show_C3_1 = new QLabel(centralwidget);
        Show_C3_1->setObjectName(QString::fromUtf8("Show_C3_1"));
        Show_C3_1->setGeometry(QRect(330, 390, 41, 31));
        Show_C3_1->setFont(font);
        line_9 = new QFrame(centralwidget);
        line_9->setObjectName(QString::fromUtf8("line_9"));
        line_9->setEnabled(true);
        line_9->setGeometry(QRect(228, 375, 148, 20));
        line_9->setFont(font2);
        line_9->setFrameShape(QFrame::HLine);
        line_9->setFrameShadow(QFrame::Sunken);
        Show_Sum3_1 = new QLabel(centralwidget);
        Show_Sum3_1->setObjectName(QString::fromUtf8("Show_Sum3_1"));
        Show_Sum3_1->setGeometry(QRect(230, 390, 41, 31));
        Show_Sum3_1->setFont(font);
        Show_Sum1_1 = new QLabel(centralwidget);
        Show_Sum1_1->setObjectName(QString::fromUtf8("Show_Sum1_1"));
        Show_Sum1_1->setGeometry(QRect(230, 300, 41, 31));
        Show_Sum1_1->setFont(font);
        Show_Sum1_1->setFocusPolicy(Qt::NoFocus);
        Show_Sum1_1->setLayoutDirection(Qt::LeftToRight);
        Show_B1_1 = new QLabel(centralwidget);
        Show_B1_1->setObjectName(QString::fromUtf8("Show_B1_1"));
        Show_B1_1->setGeometry(QRect(280, 300, 41, 31));
        Show_B1_1->setFont(font);
        Show_B3_1 = new QLabel(centralwidget);
        Show_B3_1->setObjectName(QString::fromUtf8("Show_B3_1"));
        Show_B3_1->setGeometry(QRect(280, 390, 41, 31));
        Show_B3_1->setFont(font);
        line_10 = new QFrame(centralwidget);
        line_10->setObjectName(QString::fromUtf8("line_10"));
        line_10->setGeometry(QRect(370, 290, 16, 141));
        line_10->setFrameShape(QFrame::VLine);
        line_10->setFrameShadow(QFrame::Sunken);
        line_11 = new QFrame(centralwidget);
        line_11->setObjectName(QString::fromUtf8("line_11"));
        line_11->setEnabled(true);
        line_11->setGeometry(QRect(228, 327, 148, 20));
        line_11->setFont(font2);
        line_11->setFrameShape(QFrame::HLine);
        line_11->setFrameShadow(QFrame::Sunken);
        Show_Sum2_1 = new QLabel(centralwidget);
        Show_Sum2_1->setObjectName(QString::fromUtf8("Show_Sum2_1"));
        Show_Sum2_1->setGeometry(QRect(230, 350, 41, 31));
        Show_Sum2_1->setFont(font);
        Show_C1_1 = new QLabel(centralwidget);
        Show_C1_1->setObjectName(QString::fromUtf8("Show_C1_1"));
        Show_C1_1->setGeometry(QRect(330, 300, 41, 31));
        Show_C1_1->setFont(font);
        line_12 = new QFrame(centralwidget);
        line_12->setObjectName(QString::fromUtf8("line_12"));
        line_12->setEnabled(true);
        line_12->setGeometry(QRect(228, 280, 148, 20));
        line_12->setFont(font2);
        line_12->setFrameShape(QFrame::HLine);
        line_12->setFrameShadow(QFrame::Sunken);
        Show_C2_1 = new QLabel(centralwidget);
        Show_C2_1->setObjectName(QString::fromUtf8("Show_C2_1"));
        Show_C2_1->setGeometry(QRect(330, 350, 41, 31));
        Show_C2_1->setFont(font);
        line_13 = new QFrame(centralwidget);
        line_13->setObjectName(QString::fromUtf8("line_13"));
        line_13->setEnabled(true);
        line_13->setGeometry(QRect(228, 420, 148, 20));
        line_13->setFont(font2);
        line_13->setFrameShape(QFrame::HLine);
        line_13->setFrameShadow(QFrame::Sunken);
        line_14 = new QFrame(centralwidget);
        line_14->setObjectName(QString::fromUtf8("line_14"));
        line_14->setGeometry(QRect(270, 290, 16, 141));
        line_14->setFrameShape(QFrame::VLine);
        line_14->setFrameShadow(QFrame::Sunken);
        line_15 = new QFrame(centralwidget);
        line_15->setObjectName(QString::fromUtf8("line_15"));
        line_15->setGeometry(QRect(220, 290, 16, 141));
        line_15->setFrameShape(QFrame::VLine);
        line_15->setFrameShadow(QFrame::Sunken);
        line_16 = new QFrame(centralwidget);
        line_16->setObjectName(QString::fromUtf8("line_16"));
        line_16->setGeometry(QRect(320, 290, 16, 141));
        line_16->setFrameShape(QFrame::VLine);
        line_16->setFrameShadow(QFrame::Sunken);
        Show_B2_1 = new QLabel(centralwidget);
        Show_B2_1->setObjectName(QString::fromUtf8("Show_B2_1"));
        Show_B2_1->setGeometry(QRect(280, 350, 41, 31));
        Show_B2_1->setFont(font);
        Show_Sum2_2 = new QLabel(centralwidget);
        Show_Sum2_2->setObjectName(QString::fromUtf8("Show_Sum2_2"));
        Show_Sum2_2->setGeometry(QRect(470, 350, 41, 31));
        Show_Sum2_2->setFont(font);
        line_17 = new QFrame(centralwidget);
        line_17->setObjectName(QString::fromUtf8("line_17"));
        line_17->setEnabled(true);
        line_17->setGeometry(QRect(418, 375, 148, 20));
        line_17->setFont(font2);
        line_17->setFrameShape(QFrame::HLine);
        line_17->setFrameShadow(QFrame::Sunken);
        line_18 = new QFrame(centralwidget);
        line_18->setObjectName(QString::fromUtf8("line_18"));
        line_18->setGeometry(QRect(410, 290, 16, 141));
        line_18->setFrameShape(QFrame::VLine);
        line_18->setFrameShadow(QFrame::Sunken);
        Show_C1_2 = new QLabel(centralwidget);
        Show_C1_2->setObjectName(QString::fromUtf8("Show_C1_2"));
        Show_C1_2->setGeometry(QRect(520, 300, 41, 31));
        Show_C1_2->setFont(font);
        Show_A3_2 = new QLabel(centralwidget);
        Show_A3_2->setObjectName(QString::fromUtf8("Show_A3_2"));
        Show_A3_2->setGeometry(QRect(420, 390, 41, 31));
        Show_A3_2->setFont(font);
        Show_A2_2 = new QLabel(centralwidget);
        Show_A2_2->setObjectName(QString::fromUtf8("Show_A2_2"));
        Show_A2_2->setGeometry(QRect(420, 350, 41, 31));
        Show_A2_2->setFont(font);
        line_19 = new QFrame(centralwidget);
        line_19->setObjectName(QString::fromUtf8("line_19"));
        line_19->setGeometry(QRect(510, 290, 16, 141));
        line_19->setFrameShape(QFrame::VLine);
        line_19->setFrameShadow(QFrame::Sunken);
        line_20 = new QFrame(centralwidget);
        line_20->setObjectName(QString::fromUtf8("line_20"));
        line_20->setEnabled(true);
        line_20->setGeometry(QRect(418, 327, 148, 20));
        line_20->setFont(font2);
        line_20->setFrameShape(QFrame::HLine);
        line_20->setFrameShadow(QFrame::Sunken);
        Show_Sum3_2 = new QLabel(centralwidget);
        Show_Sum3_2->setObjectName(QString::fromUtf8("Show_Sum3_2"));
        Show_Sum3_2->setGeometry(QRect(470, 390, 41, 31));
        Show_Sum3_2->setFont(font);
        Show_A1_2 = new QLabel(centralwidget);
        Show_A1_2->setObjectName(QString::fromUtf8("Show_A1_2"));
        Show_A1_2->setGeometry(QRect(420, 300, 41, 31));
        Show_A1_2->setFont(font);
        Show_A1_2->setFocusPolicy(Qt::NoFocus);
        Show_A1_2->setLayoutDirection(Qt::LeftToRight);
        line_21 = new QFrame(centralwidget);
        line_21->setObjectName(QString::fromUtf8("line_21"));
        line_21->setEnabled(true);
        line_21->setGeometry(QRect(418, 280, 148, 20));
        line_21->setFont(font2);
        line_21->setFrameShape(QFrame::HLine);
        line_21->setFrameShadow(QFrame::Sunken);
        Show_C2_2 = new QLabel(centralwidget);
        Show_C2_2->setObjectName(QString::fromUtf8("Show_C2_2"));
        Show_C2_2->setGeometry(QRect(520, 350, 41, 31));
        Show_C2_2->setFont(font);
        Show_Sum1_2 = new QLabel(centralwidget);
        Show_Sum1_2->setObjectName(QString::fromUtf8("Show_Sum1_2"));
        Show_Sum1_2->setGeometry(QRect(470, 300, 41, 31));
        Show_Sum1_2->setFont(font);
        line_22 = new QFrame(centralwidget);
        line_22->setObjectName(QString::fromUtf8("line_22"));
        line_22->setGeometry(QRect(460, 290, 16, 141));
        line_22->setFrameShape(QFrame::VLine);
        line_22->setFrameShadow(QFrame::Sunken);
        line_23 = new QFrame(centralwidget);
        line_23->setObjectName(QString::fromUtf8("line_23"));
        line_23->setGeometry(QRect(560, 290, 16, 141));
        line_23->setFrameShape(QFrame::VLine);
        line_23->setFrameShadow(QFrame::Sunken);
        line_25 = new QFrame(centralwidget);
        line_25->setObjectName(QString::fromUtf8("line_25"));
        line_25->setEnabled(true);
        line_25->setGeometry(QRect(418, 420, 148, 20));
        line_25->setFont(font2);
        line_25->setFrameShape(QFrame::HLine);
        line_25->setFrameShadow(QFrame::Sunken);
        Show_C3_2 = new QLabel(centralwidget);
        Show_C3_2->setObjectName(QString::fromUtf8("Show_C3_2"));
        Show_C3_2->setGeometry(QRect(520, 390, 41, 31));
        Show_C3_2->setFont(font);
        Show_Sum3_3 = new QLabel(centralwidget);
        Show_Sum3_3->setObjectName(QString::fromUtf8("Show_Sum3_3"));
        Show_Sum3_3->setGeometry(QRect(712, 390, 41, 31));
        Show_Sum3_3->setFont(font);
        Show_B1_3 = new QLabel(centralwidget);
        Show_B1_3->setObjectName(QString::fromUtf8("Show_B1_3"));
        Show_B1_3->setGeometry(QRect(662, 300, 41, 31));
        Show_B1_3->setFont(font);
        Show_B2_3 = new QLabel(centralwidget);
        Show_B2_3->setObjectName(QString::fromUtf8("Show_B2_3"));
        Show_B2_3->setGeometry(QRect(662, 350, 41, 31));
        Show_B2_3->setFont(font);
        line_24 = new QFrame(centralwidget);
        line_24->setObjectName(QString::fromUtf8("line_24"));
        line_24->setGeometry(QRect(652, 290, 16, 141));
        line_24->setFrameShape(QFrame::VLine);
        line_24->setFrameShadow(QFrame::Sunken);
        line_26 = new QFrame(centralwidget);
        line_26->setObjectName(QString::fromUtf8("line_26"));
        line_26->setGeometry(QRect(702, 290, 16, 141));
        line_26->setFrameShape(QFrame::VLine);
        line_26->setFrameShadow(QFrame::Sunken);
        Show_A1_3 = new QLabel(centralwidget);
        Show_A1_3->setObjectName(QString::fromUtf8("Show_A1_3"));
        Show_A1_3->setGeometry(QRect(612, 300, 41, 31));
        Show_A1_3->setFont(font);
        Show_A1_3->setFocusPolicy(Qt::NoFocus);
        Show_A1_3->setLayoutDirection(Qt::LeftToRight);
        line_27 = new QFrame(centralwidget);
        line_27->setObjectName(QString::fromUtf8("line_27"));
        line_27->setEnabled(true);
        line_27->setGeometry(QRect(610, 375, 148, 20));
        line_27->setFont(font2);
        line_27->setFrameShape(QFrame::HLine);
        line_27->setFrameShadow(QFrame::Sunken);
        Show_A3_3 = new QLabel(centralwidget);
        Show_A3_3->setObjectName(QString::fromUtf8("Show_A3_3"));
        Show_A3_3->setGeometry(QRect(612, 390, 41, 31));
        Show_A3_3->setFont(font);
        Show_A2_3 = new QLabel(centralwidget);
        Show_A2_3->setObjectName(QString::fromUtf8("Show_A2_3"));
        Show_A2_3->setGeometry(QRect(612, 350, 41, 31));
        Show_A2_3->setFont(font);
        Show_B3_3 = new QLabel(centralwidget);
        Show_B3_3->setObjectName(QString::fromUtf8("Show_B3_3"));
        Show_B3_3->setGeometry(QRect(662, 390, 41, 31));
        Show_B3_3->setFont(font);
        Show_Sum2_3 = new QLabel(centralwidget);
        Show_Sum2_3->setObjectName(QString::fromUtf8("Show_Sum2_3"));
        Show_Sum2_3->setGeometry(QRect(712, 350, 41, 31));
        Show_Sum2_3->setFont(font);
        line_28 = new QFrame(centralwidget);
        line_28->setObjectName(QString::fromUtf8("line_28"));
        line_28->setGeometry(QRect(602, 290, 16, 141));
        line_28->setFrameShape(QFrame::VLine);
        line_28->setFrameShadow(QFrame::Sunken);
        line_29 = new QFrame(centralwidget);
        line_29->setObjectName(QString::fromUtf8("line_29"));
        line_29->setGeometry(QRect(752, 290, 16, 141));
        line_29->setFrameShape(QFrame::VLine);
        line_29->setFrameShadow(QFrame::Sunken);
        line_30 = new QFrame(centralwidget);
        line_30->setObjectName(QString::fromUtf8("line_30"));
        line_30->setEnabled(true);
        line_30->setGeometry(QRect(610, 420, 148, 20));
        line_30->setFont(font2);
        line_30->setFrameShape(QFrame::HLine);
        line_30->setFrameShadow(QFrame::Sunken);
        Show_Sum1_3 = new QLabel(centralwidget);
        Show_Sum1_3->setObjectName(QString::fromUtf8("Show_Sum1_3"));
        Show_Sum1_3->setGeometry(QRect(712, 300, 41, 31));
        Show_Sum1_3->setFont(font);
        line_31 = new QFrame(centralwidget);
        line_31->setObjectName(QString::fromUtf8("line_31"));
        line_31->setEnabled(true);
        line_31->setGeometry(QRect(610, 280, 148, 20));
        line_31->setFont(font2);
        line_31->setFrameShape(QFrame::HLine);
        line_31->setFrameShadow(QFrame::Sunken);
        line_32 = new QFrame(centralwidget);
        line_32->setObjectName(QString::fromUtf8("line_32"));
        line_32->setEnabled(true);
        line_32->setGeometry(QRect(610, 327, 148, 20));
        line_32->setFont(font2);
        line_32->setFrameShape(QFrame::HLine);
        line_32->setFrameShadow(QFrame::Sunken);
        Show_A1_5 = new QLabel(centralwidget);
        Show_A1_5->setObjectName(QString::fromUtf8("Show_A1_5"));
        Show_A1_5->setGeometry(QRect(10, 260, 41, 31));
        Show_A1_5->setFont(font);
        Show_A1_5->setFocusPolicy(Qt::NoFocus);
        Show_A1_5->setLayoutDirection(Qt::LeftToRight);
        pushButton = new QPushButton(centralwidget);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(700, 0, 81, 71));
        Show_D = new QLabel(centralwidget);
        Show_D->setObjectName(QString::fromUtf8("Show_D"));
        Show_D->setGeometry(QRect(60, 260, 41, 31));
        Show_D->setFont(font);
        Show_D->setFocusPolicy(Qt::NoFocus);
        Show_D->setLayoutDirection(Qt::LeftToRight);
        Show_A1_10 = new QLabel(centralwidget);
        Show_A1_10->setObjectName(QString::fromUtf8("Show_A1_10"));
        Show_A1_10->setGeometry(QRect(190, 260, 71, 31));
        Show_A1_10->setFont(font);
        Show_A1_10->setFocusPolicy(Qt::NoFocus);
        Show_A1_10->setLayoutDirection(Qt::LeftToRight);
        Show_D1 = new QLabel(centralwidget);
        Show_D1->setObjectName(QString::fromUtf8("Show_D1"));
        Show_D1->setGeometry(QRect(260, 260, 41, 31));
        Show_D1->setFont(font);
        Show_D1->setFocusPolicy(Qt::NoFocus);
        Show_D1->setLayoutDirection(Qt::LeftToRight);
        Show_A1_6 = new QLabel(centralwidget);
        Show_A1_6->setObjectName(QString::fromUtf8("Show_A1_6"));
        Show_A1_6->setGeometry(QRect(380, 260, 61, 31));
        Show_A1_6->setFont(font);
        Show_A1_6->setFocusPolicy(Qt::NoFocus);
        Show_A1_6->setLayoutDirection(Qt::LeftToRight);
        Show_D2 = new QLabel(centralwidget);
        Show_D2->setObjectName(QString::fromUtf8("Show_D2"));
        Show_D2->setGeometry(QRect(450, 260, 41, 31));
        Show_D2->setFont(font);
        Show_D2->setFocusPolicy(Qt::NoFocus);
        Show_D2->setLayoutDirection(Qt::LeftToRight);
        Show_A1_7 = new QLabel(centralwidget);
        Show_A1_7->setObjectName(QString::fromUtf8("Show_A1_7"));
        Show_A1_7->setGeometry(QRect(570, 260, 61, 31));
        Show_A1_7->setFont(font);
        Show_A1_7->setFocusPolicy(Qt::NoFocus);
        Show_A1_7->setLayoutDirection(Qt::LeftToRight);
        Show_D3 = new QLabel(centralwidget);
        Show_D3->setObjectName(QString::fromUtf8("Show_D3"));
        Show_D3->setGeometry(QRect(640, 260, 41, 31));
        Show_D3->setFont(font);
        Show_D3->setFocusPolicy(Qt::NoFocus);
        Show_D3->setLayoutDirection(Qt::LeftToRight);
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 780, 26));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);
        toolBar = new QToolBar(MainWindow);
        toolBar->setObjectName(QString::fromUtf8("toolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, toolBar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "MainWindow", nullptr));
        label_2->setText(QCoreApplication::translate("MainWindow", "x", nullptr));
        label_3->setText(QCoreApplication::translate("MainWindow", "y", nullptr));
        label_4->setText(QCoreApplication::translate("MainWindow", "+", nullptr));
        label_5->setText(QCoreApplication::translate("MainWindow", "z", nullptr));
        label_6->setText(QCoreApplication::translate("MainWindow", "+", nullptr));
        label_7->setText(QCoreApplication::translate("MainWindow", "=", nullptr));
        label_8->setText(QCoreApplication::translate("MainWindow", "y", nullptr));
        label_9->setText(QCoreApplication::translate("MainWindow", "+", nullptr));
        label_10->setText(QCoreApplication::translate("MainWindow", "z", nullptr));
        label_11->setText(QCoreApplication::translate("MainWindow", "=", nullptr));
        label_12->setText(QCoreApplication::translate("MainWindow", "+", nullptr));
        label_13->setText(QCoreApplication::translate("MainWindow", "x", nullptr));
        label_14->setText(QCoreApplication::translate("MainWindow", "x", nullptr));
        label_15->setText(QCoreApplication::translate("MainWindow", "+", nullptr));
        label_16->setText(QCoreApplication::translate("MainWindow", "=", nullptr));
        label_17->setText(QCoreApplication::translate("MainWindow", "+", nullptr));
        label_18->setText(QCoreApplication::translate("MainWindow", "y", nullptr));
        label_19->setText(QCoreApplication::translate("MainWindow", "z", nullptr));
        label_20->setText(QCoreApplication::translate("MainWindow", "{", nullptr));
        pushButton_2->setText(QCoreApplication::translate("MainWindow", "\320\237\320\276\320\272\320\260\320\267\320\260\321\202\321\214 \320\272\320\276\321\200\320\275\320\270", nullptr));
        pushButton_3->setText(QCoreApplication::translate("MainWindow", "\320\237\320\276\320\272\320\260\320\267\320\260\321\202\321\214 \320\275\320\260\321\205\320\276\320\266\320\264\320\265\320\275\320\270\321\217 D", nullptr));
        Show_A1->setText(QString());
        Show_A2->setText(QString());
        Show_A3->setText(QString());
        Show_B1->setText(QString());
        Show_B2->setText(QString());
        Show_B3->setText(QString());
        Show_C1->setText(QString());
        Show_C2->setText(QString());
        Show_C3->setText(QString());
        Show_C3_1->setText(QString());
        Show_Sum3_1->setText(QString());
        Show_Sum1_1->setText(QString());
        Show_B1_1->setText(QString());
        Show_B3_1->setText(QString());
        Show_Sum2_1->setText(QString());
        Show_C1_1->setText(QString());
        Show_C2_1->setText(QString());
        Show_B2_1->setText(QString());
        Show_Sum2_2->setText(QString());
        Show_C1_2->setText(QString());
        Show_A3_2->setText(QString());
        Show_A2_2->setText(QString());
        Show_Sum3_2->setText(QString());
        Show_A1_2->setText(QString());
        Show_C2_2->setText(QString());
        Show_Sum1_2->setText(QString());
        Show_C3_2->setText(QString());
        Show_Sum3_3->setText(QString());
        Show_B1_3->setText(QString());
        Show_B2_3->setText(QString());
        Show_A1_3->setText(QString());
        Show_A3_3->setText(QString());
        Show_A2_3->setText(QString());
        Show_B3_3->setText(QString());
        Show_Sum2_3->setText(QString());
        Show_Sum1_3->setText(QString());
        Show_A1_5->setText(QCoreApplication::translate("MainWindow", "D =", nullptr));
        pushButton->setText(QCoreApplication::translate("MainWindow", "\320\237\320\276\320\264\321\201\320\272\320\260\320\267\320\272\320\260", nullptr));
        Show_D->setText(QString());
        Show_A1_10->setText(QCoreApplication::translate("MainWindow", "D1 =", nullptr));
        Show_D1->setText(QString());
        Show_A1_6->setText(QCoreApplication::translate("MainWindow", "D2 =", nullptr));
        Show_D2->setText(QString());
        Show_A1_7->setText(QCoreApplication::translate("MainWindow", "D3 =", nullptr));
        Show_D3->setText(QString());
        toolBar->setWindowTitle(QCoreApplication::translate("MainWindow", "toolBar", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
